// AUTO-GENERATED by feat emit — do not edit manually
// Source: packages/feat-core/parse.feat (SPEC-CORE-001)
// Language: feat 1.0 · Emitter: @mmmnt/feat-emit-ts@0.1.1
// Inputs-hash: sha256:8ac50588475d1a92b4b1e4b57dee0c6573b1d2a11fd7c9d6837ee2849a218486

import { describe, it, beforeAll, afterAll } from "vitest";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHarness, type Harness, type HarnessCase, type InlineData } from "@mmmnt/feat-runtime";

// Location-independent: the config resolves relative to THIS file, and the
// process runs from the project root (the canonical execution cwd for payload paths).
const CONFIG_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../feat.config.json");

const INLINE: InlineData = {
  "schemas": {
    "ParseInput": {
      "type": "object",
      "required": [
        "spec",
        "config"
      ],
      "additionalProperties": false,
      "properties": {
        "spec": {
          "type": "string",
          "minLength": 1
        },
        "config": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "BuiltSpec": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "$id": "https://feat.dev/schemas/builtspec.json",
      "title": "BuiltSpec IR",
      "description": "The language-neutral intermediate representation produced by parsing a .feat file (F13 hedge: a future Go toolchain binds to this same contract). Corpus .ir.json fixtures instantiate this schema and are the parser's ground truth. TS types in @mmmnt/feat-types derive from this document.",
      "type": "object",
      "required": [
        "featVersion",
        "identity",
        "construct",
        "enforce",
        "contract",
        "scenarios"
      ],
      "additionalProperties": false,
      "properties": {
        "featVersion": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+$"
        },
        "identity": {
          "type": "object",
          "required": [
            "id",
            "name",
            "context",
            "aggregate",
            "type",
            "status"
          ],
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "pattern": "^SPEC-[A-Z0-9]+-[0-9]+$"
            },
            "name": {
              "type": "string"
            },
            "context": {
              "type": "string"
            },
            "aggregate": {
              "type": "string"
            },
            "type": {
              "enum": [
                "command",
                "query",
                "policy",
                "projection",
                "saga",
                "infrastructure",
                "integration",
                "scaffold"
              ]
            },
            "status": {
              "enum": [
                "draft",
                "agreed",
                "built",
                "verified"
              ]
            }
          }
        },
        "construct": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/constructInstruction"
          }
        },
        "enforce": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/enforceStep"
          }
        },
        "contract": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/contractReference"
          }
        },
        "scenarios": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/scenario"
          }
        }
      },
      "definitions": {
        "constructInstruction": {
          "type": "object",
          "required": [
            "kind"
          ],
          "oneOf": [
            {
              "properties": {
                "kind": {
                  "const": "handler"
                },
                "path": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "path"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "import"
                },
                "symbol": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "symbol",
                "path"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "register"
                },
                "registrationKind": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "registrationKind",
                "name",
                "path"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "emitsTo"
                },
                "streamPattern": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "streamPattern"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "touches"
                },
                "glob": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "glob"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "needs"
                },
                "specId": {
                  "type": "string",
                  "pattern": "^SPEC-[A-Z0-9]+-[0-9]+$"
                }
              },
              "required": [
                "kind",
                "specId"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "custom"
                },
                "text": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "text"
              ],
              "additionalProperties": false
            }
          ]
        },
        "enforceStep": {
          "type": "object",
          "required": [
            "kind",
            "text"
          ],
          "additionalProperties": false,
          "properties": {
            "kind": {
              "enum": [
                "validate",
                "load",
                "apply",
                "onSuccess",
                "onRejection",
                "constraint",
                "rejects"
              ]
            },
            "rejectionId": {
              "type": "string",
              "description": "Present iff kind is 'rejects' (ADR-0008); validated two-way against scenario rejection IDs."
            },
            "text": {
              "type": "string",
              "description": "The directive line (for 'rejects': the freeform reason)."
            }
          }
        },
        "contractReference": {
          "type": "object",
          "required": [
            "kind"
          ],
          "oneOf": [
            {
              "properties": {
                "kind": {
                  "enum": [
                    "input",
                    "response",
                    "event",
                    "record",
                    "error"
                  ]
                },
                "schemaName": {
                  "type": "string"
                },
                "from": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "schemaName"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "kind": {
                  "const": "stream"
                },
                "pattern": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "pattern"
              ],
              "additionalProperties": false
            }
          ]
        },
        "scenario": {
          "type": "object",
          "required": [
            "name",
            "prediction"
          ],
          "oneOf": [
            {
              "required": [
                "when"
              ]
            },
            {
              "required": [
                "delivers"
              ]
            }
          ],
          "additionalProperties": false,
          "description": "Scenario names are unique within a spec (parser-enforced, ADR-0010) and serve as failure anchors. Trigger: when (command/query) XOR delivers (projection/policy/saga) — per-type enforcement per ADR-0011.",
          "properties": {
            "name": {
              "type": "string"
            },
            "given": {
              "$ref": "#/definitions/given"
            },
            "when": {
              "$ref": "#/definitions/invocation"
            },
            "delivers": {
              "type": "array",
              "minItems": 1,
              "description": "Ordered event deliveries (ADR-0011); multiple entries = saga sequence. Excluded from capture.",
              "items": {
                "$ref": "#/definitions/delivery"
              }
            },
            "prediction": {
              "$ref": "#/definitions/prediction"
            },
            "examples": {
              "type": "array",
              "minItems": 1,
              "description": "Scenario-outline rows (ADR-0012): one derived test case per row; keys are placeholder names.",
              "items": {
                "type": "object",
                "minProperties": 1
              }
            },
            "loc": {
              "$ref": "#/definitions/loc"
            }
          }
        },
        "delivery": {
          "type": "object",
          "required": [
            "event",
            "payload",
            "service"
          ],
          "additionalProperties": false,
          "properties": {
            "event": {
              "type": "string"
            },
            "payload": {
              "type": "object"
            },
            "service": {
              "type": "string"
            }
          }
        },
        "loc": {
          "type": "object",
          "description": "Optional source location stamped by the parser (ADR-0010). Omitted in hand-authored fixtures; stripped before INV-1 determinism comparison.",
          "required": [
            "line"
          ],
          "additionalProperties": false,
          "properties": {
            "line": {
              "type": "integer",
              "minimum": 1
            },
            "column": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "given": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "clock": {
              "type": "string",
              "description": "ISO-8601 timestamp freezing scenario time (ADR-0012); v1 honored by the handler adapter only."
            },
            "context": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Freeform lines, verbatim."
            },
            "executes": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/invocation"
              }
            },
            "seeds": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/seed"
              }
            }
          }
        },
        "invocation": {
          "type": "object",
          "required": [
            "command",
            "payload"
          ],
          "additionalProperties": false,
          "properties": {
            "command": {
              "type": "string"
            },
            "actor": {
              "type": "string",
              "description": "Actor name from response.actors, or reserved 'anonymous' (ADR-0012). Omitted = actors.default."
            },
            "payload": {
              "type": "object",
              "description": "Inline JSON; outline placeholders appear as {\"$placeholder\": \"<name>\"} (ADR-0012)."
            }
          }
        },
        "seed": {
          "type": "object",
          "required": [
            "service"
          ],
          "additionalProperties": false,
          "properties": {
            "service": {
              "type": "string"
            },
            "records": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "type",
                  "values"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "schemaName": {
                    "type": "string"
                  },
                  "values": {
                    "type": "object"
                  }
                }
              }
            },
            "fixture": {
              "type": "string",
              "description": "Path to a JSON fixture file (bulk form)."
            }
          },
          "oneOf": [
            {
              "required": [
                "records"
              ]
            },
            {
              "required": [
                "fixture"
              ]
            }
          ]
        },
        "prediction": {
          "type": "object",
          "required": [
            "type"
          ],
          "additionalProperties": false,
          "description": "response: required for when:-triggered scenarios, absent for deliver-triggered (ADR-0011). services: required with one entry per configured key (INV-6) except type query, where services are implicitly zero (has [X] is a parse error) and the property is omitted.",
          "properties": {
            "type": {
              "enum": [
                "success",
                "rejection",
                "error"
              ]
            },
            "rejectionId": {
              "type": "string"
            },
            "errorCode": {
              "type": "string"
            },
            "response": {
              "type": "object",
              "required": [
                "status",
                "schemaName"
              ],
              "additionalProperties": false,
              "not": {
                "required": [
                  "valueBlock",
                  "golden"
                ]
              },
              "properties": {
                "status": {
                  "type": [
                    "integer",
                    "string"
                  ]
                },
                "schemaName": {
                  "type": "string"
                },
                "valueBlock": {
                  "$ref": "#/definitions/valueBlock"
                },
                "golden": {
                  "type": "string",
                  "description": "Golden-fixture path (ADR-0013); deep structural equality; exclusive with valueBlock."
                }
              }
            },
            "services": {
              "type": "object",
              "minProperties": 1,
              "additionalProperties": {
                "type": "object",
                "additionalProperties": false,
                "anyOf": [
                  {
                    "required": [
                      "records"
                    ]
                  },
                  {
                    "required": [
                      "contains"
                    ]
                  }
                ],
                "properties": {
                  "ordering": {
                    "enum": [
                      "ordered",
                      "unordered"
                    ],
                    "description": "Present only when explicitly overridden (ADR-0004); otherwise derive resolves from the service's consistency model."
                  },
                  "records": {
                    "type": "array",
                    "description": "Captured-write assertions (`has`).",
                    "items": {
                      "$ref": "#/definitions/predictedRecord"
                    }
                  },
                  "contains": {
                    "type": "array",
                    "minItems": 1,
                    "description": "Resulting-state assertions via adapter read() (`contains`, ADR-0011).",
                    "items": {
                      "$ref": "#/definitions/predictedRecord"
                    }
                  }
                }
              }
            }
          }
        },
        "predictedRecord": {
          "type": "object",
          "required": [
            "type",
            "schemaName"
          ],
          "additionalProperties": false,
          "not": {
            "required": [
              "valueBlock",
              "golden"
            ]
          },
          "properties": {
            "type": {
              "type": "string"
            },
            "schemaName": {
              "type": "string"
            },
            "valueBlock": {
              "$ref": "#/definitions/valueBlock"
            },
            "golden": {
              "type": "string",
              "description": "Golden-fixture path (ADR-0013); deep structural equality; exclusive with valueBlock."
            }
          }
        },
        "valueBlock": {
          "type": "object",
          "description": "Field path → matcher (ADR-0002).",
          "additionalProperties": {
            "$ref": "#/definitions/matcher"
          }
        },
        "matcher": {
          "oneOf": [
            {
              "type": "object",
              "required": [
                "matcher"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "literal"
                },
                "value": {
                  "type": [
                    "string",
                    "number",
                    "boolean",
                    "null"
                  ]
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "path"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "whenRef"
                },
                "path": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "path"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "deliverRef"
                },
                "path": {
                  "type": "string"
                },
                "index": {
                  "type": "integer",
                  "minimum": 0,
                  "description": "Required when the scenario has multiple deliveries (saga sequences)."
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "any"
                },
                "ofType": {
                  "enum": [
                    "uuid",
                    "timestamp",
                    "string",
                    "number",
                    "boolean"
                  ]
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "pattern"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "regex"
                },
                "pattern": {
                  "oneOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "object",
                      "required": [
                        "$placeholder"
                      ],
                      "additionalProperties": false,
                      "properties": {
                        "$placeholder": {
                          "type": "string"
                        }
                      },
                      "description": "Outline placeholder in the matching-argument position (ADR-0012 addendum); derive substitutes the row value."
                    }
                  ]
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "absent"
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "name"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "placeholder"
                },
                "name": {
                  "type": "string",
                  "description": "Outline placeholder name; resolved per examples row (ADR-0012)."
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "path"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "goldenFixture"
                },
                "path": {
                  "type": "string",
                  "description": "Golden fixture path relative to the spec (ADR-0013); deep structural equality."
                }
              }
            },
            {
              "type": "object",
              "required": [
                "matcher",
                "fields"
              ],
              "additionalProperties": false,
              "properties": {
                "matcher": {
                  "const": "nested"
                },
                "fields": {
                  "$ref": "#/definitions/valueBlock"
                }
              }
            }
          ]
        }
      }
    },
    "ParseError": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "enum": [
            "MISSING_PRAGMA",
            "UNSUPPORTED_VERSION",
            "MALFORMED_SYNTAX",
            "UNKNOWN_SERVICE_KEY",
            "UNKNOWN_COMMAND",
            "UNDECLARED_SCHEMA",
            "UNKNOWN_ACTOR",
            "DUPLICATE_SCENARIO_NAME",
            "TRIGGER_MISMATCH",
            "QUERY_SIDE_EFFECT",
            "INCOMPLETE_PREDICTION",
            "MISSING_MINIMUM"
          ]
        },
        "message": {
          "type": "string"
        },
        "line": {
          "type": "integer",
          "minimum": 1
        },
        "hint": {
          "type": "string"
        }
      }
    }
  },
  "goldens": {
    "../../corpus/create-flow/create-flow.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-AUT-001",
        "name": "CreateFlow Command Handler",
        "context": "Automation",
        "aggregate": "Flow",
        "type": "command",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "features/create-flow/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "features/create-flow/**"
        },
        {
          "kind": "touches",
          "glob": "resolvers/mutations.ts"
        },
        {
          "kind": "import",
          "symbol": "FlowAggregate",
          "path": "core/domain/flow-aggregate"
        },
        {
          "kind": "import",
          "symbol": "FlowRepository",
          "path": "core/domain/flow-repository"
        },
        {
          "kind": "import",
          "symbol": "CreateFlowInput",
          "path": "core/contracts/commands"
        },
        {
          "kind": "import",
          "symbol": "FlowCreatedEvent",
          "path": "core/contracts/events"
        },
        {
          "kind": "register",
          "registrationKind": "mutation",
          "name": "createFlow",
          "path": "resolvers/mutations.ts"
        },
        {
          "kind": "emitsTo",
          "streamPattern": "automation-flow-{flowId}"
        }
      ],
      "enforce": [
        {
          "kind": "validate",
          "text": "validate input against CreateFlowInput"
        },
        {
          "kind": "load",
          "text": "load FlowAggregate from FlowRepository by tenantId"
        },
        {
          "kind": "apply",
          "text": "apply CreateFlow through FlowAggregate.create factory method"
        },
        {
          "kind": "onSuccess",
          "text": "on success emit FlowCreated to event stream"
        },
        {
          "kind": "onRejection",
          "text": "on rejection return error per contract error format"
        },
        {
          "kind": "rejects",
          "rejectionId": "UNIQUE_NAME",
          "text": "a flow with this name already exists for the tenant"
        },
        {
          "kind": "constraint",
          "text": "Lambda cannot write directly to Kurrent."
        },
        {
          "kind": "constraint",
          "text": "Handler is a pure function: input -> Result<FlowCreated, FlowError>."
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "CreateFlowInput"
        },
        {
          "kind": "response",
          "schemaName": "FlowCreatedResponse"
        },
        {
          "kind": "event",
          "schemaName": "FlowCreatedEvent"
        },
        {
          "kind": "error",
          "schemaName": "RFC7807",
          "from": "contracts/adrs/error-format"
        },
        {
          "kind": "stream",
          "pattern": "automation-flow-{flowId}"
        }
      ],
      "scenarios": [
        {
          "name": "successful flow creation",
          "given": {
            "context": [
              "No flow named \"Welcome\" exists for this tenant."
            ]
          },
          "when": {
            "command": "CreateFlow",
            "payload": {
              "name": "Welcome",
              "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 201,
              "schemaName": "FlowCreatedResponse",
              "valueBlock": {
                "flowId": {
                  "matcher": "any",
                  "ofType": "uuid"
                },
                "name": {
                  "matcher": "whenRef",
                  "path": "name"
                }
              }
            },
            "services": {
              "eventStore": {
                "records": [
                  {
                    "type": "FlowCreated",
                    "schemaName": "FlowCreatedEvent",
                    "valueBlock": {
                      "name": {
                        "matcher": "whenRef",
                        "path": "name"
                      },
                      "tenantId": {
                        "matcher": "whenRef",
                        "path": "tenantId"
                      },
                      "flowId": {
                        "matcher": "any",
                        "ofType": "uuid"
                      },
                      "createdAt": {
                        "matcher": "any",
                        "ofType": "timestamp"
                      }
                    }
                  }
                ]
              },
              "projectionStore": {
                "records": []
              },
              "eventBroker": {
                "records": []
              }
            }
          }
        },
        {
          "name": "rejects duplicate flow name",
          "given": {
            "context": [
              "A flow with this name already exists for the tenant."
            ],
            "executes": [
              {
                "command": "CreateFlow",
                "payload": {
                  "name": "Welcome",
                  "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60"
                }
              }
            ]
          },
          "when": {
            "command": "CreateFlow",
            "payload": {
              "name": "Welcome",
              "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "UNIQUE_NAME",
            "response": {
              "status": 409,
              "schemaName": "RFC7807"
            },
            "services": {
              "eventStore": {
                "records": []
              },
              "projectionStore": {
                "records": []
              },
              "eventBroker": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/create-user/create-user.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-USR-001",
        "name": "CreateUser",
        "context": "Users",
        "aggregate": "User",
        "type": "command",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "handlers/create-user.ts"
        },
        {
          "kind": "touches",
          "glob": "handlers/**"
        },
        {
          "kind": "import",
          "symbol": "UserRepository",
          "path": "repositories/user-repository"
        },
        {
          "kind": "custom",
          "text": "Uses Prisma ORM for database access."
        }
      ],
      "enforce": [
        {
          "kind": "validate",
          "text": "validate input against CreateUserInput"
        },
        {
          "kind": "constraint",
          "text": "check email uniqueness via UserRepository.findByEmail"
        },
        {
          "kind": "rejects",
          "rejectionId": "DUPLICATE_EMAIL",
          "text": "a user with this email already exists"
        },
        {
          "kind": "constraint",
          "text": "insert new user record"
        },
        {
          "kind": "constraint",
          "text": "return created user"
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "CreateUserInput"
        },
        {
          "kind": "response",
          "schemaName": "UserResponse"
        },
        {
          "kind": "record",
          "schemaName": "UserRow"
        },
        {
          "kind": "error",
          "schemaName": "ErrorResponse"
        }
      ],
      "scenarios": [
        {
          "name": "successful user creation",
          "given": {
            "context": [
              "No user with this email exists."
            ]
          },
          "when": {
            "command": "CreateUser",
            "payload": {
              "email": "alice@example.com",
              "name": "Alice"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 201,
              "schemaName": "UserResponse",
              "valueBlock": {
                "id": {
                  "matcher": "any",
                  "ofType": "uuid"
                },
                "email": {
                  "matcher": "whenRef",
                  "path": "email"
                },
                "name": {
                  "matcher": "whenRef",
                  "path": "name"
                }
              }
            },
            "services": {
              "database": {
                "records": [
                  {
                    "type": "INSERT",
                    "schemaName": "UserRow",
                    "valueBlock": {
                      "email": {
                        "matcher": "whenRef",
                        "path": "email"
                      },
                      "name": {
                        "matcher": "whenRef",
                        "path": "name"
                      },
                      "id": {
                        "matcher": "any",
                        "ofType": "uuid"
                      },
                      "status": {
                        "matcher": "literal",
                        "value": "active"
                      },
                      "deletedAt": {
                        "matcher": "absent"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "name": "rejects duplicate email",
          "given": {
            "executes": [
              {
                "command": "CreateUser",
                "payload": {
                  "email": "alice@example.com",
                  "name": "Alice"
                }
              }
            ]
          },
          "when": {
            "command": "CreateUser",
            "payload": {
              "email": "alice@example.com",
              "name": "Bob"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "DUPLICATE_EMAIL",
            "response": {
              "status": 409,
              "schemaName": "ErrorResponse",
              "valueBlock": {
                "code": {
                  "matcher": "literal",
                  "value": "DUPLICATE_EMAIL"
                }
              }
            },
            "services": {
              "database": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/tenant-at-limit/tenant-at-limit.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-AUT-002",
        "name": "CreateFlow at tenant limit",
        "context": "Automation",
        "aggregate": "Flow",
        "type": "command",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "features/create-flow/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "features/create-flow/**"
        },
        {
          "kind": "import",
          "symbol": "FlowAggregate",
          "path": "core/domain/flow-aggregate"
        }
      ],
      "enforce": [
        {
          "kind": "load",
          "text": "load FlowAggregate from FlowRepository by tenantId"
        },
        {
          "kind": "rejects",
          "rejectionId": "FLOW_LIMIT",
          "text": "the tenant's flow count has reached the plan limit"
        },
        {
          "kind": "constraint",
          "text": "The flow limit for the \"starter\" plan is 5."
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "CreateFlowInput"
        },
        {
          "kind": "record",
          "schemaName": "TenantSchema"
        },
        {
          "kind": "event",
          "schemaName": "FlowCreatedEvent"
        },
        {
          "kind": "error",
          "schemaName": "RFC7807",
          "from": "contracts/adrs/error-format"
        }
      ],
      "scenarios": [
        {
          "name": "tenant at flow limit",
          "given": {
            "context": [
              "The tenant is on the starter plan and already has 5 flows."
            ],
            "seeds": [
              {
                "service": "projectionStore",
                "records": [
                  {
                    "type": "TenantRecord",
                    "schemaName": "TenantSchema",
                    "values": {
                      "tenantId": "0b7e9c14-2d3f-4a5b-8c6d-7e8f9a0b1c2d",
                      "plan": "starter",
                      "flowCount": 5
                    }
                  }
                ]
              },
              {
                "service": "eventStore",
                "fixture": "fixtures/tenant-at-limit.events.json"
              }
            ]
          },
          "when": {
            "command": "CreateFlow",
            "payload": {
              "name": "Flow-6",
              "tenantId": "0b7e9c14-2d3f-4a5b-8c6d-7e8f9a0b1c2d"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "FLOW_LIMIT",
            "response": {
              "status": 409,
              "schemaName": "RFC7807"
            },
            "services": {
              "eventStore": {
                "records": []
              },
              "projectionStore": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/publish-order/publish-order.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-ORD-001",
        "name": "PublishOrder Saga Step",
        "context": "Fulfillment",
        "aggregate": "Order",
        "type": "command",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "sagas/publish-order/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "sagas/publish-order/**"
        },
        {
          "kind": "import",
          "symbol": "OrderAggregate",
          "path": "core/domain/order-aggregate"
        },
        {
          "kind": "emitsTo",
          "streamPattern": "fulfillment-order-{orderId}"
        }
      ],
      "enforce": [
        {
          "kind": "apply",
          "text": "apply PublishOrder through OrderAggregate.publish"
        },
        {
          "kind": "constraint",
          "text": "write OrderPublished then OrderPriced to the outbox in that order"
        },
        {
          "kind": "constraint",
          "text": "broadcast both events to the broker; broker delivery order is not guaranteed"
        },
        {
          "kind": "constraint",
          "text": "on payment-provider outage return PROVIDER_UNAVAILABLE and write nothing"
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "PublishOrderInput"
        },
        {
          "kind": "response",
          "schemaName": "OrderPublishedResponse"
        },
        {
          "kind": "event",
          "schemaName": "OrderPublishedEvent"
        },
        {
          "kind": "event",
          "schemaName": "OrderPricedEvent"
        },
        {
          "kind": "error",
          "schemaName": "RFC7807",
          "from": "contracts/adrs/error-format"
        }
      ],
      "scenarios": [
        {
          "name": "publishes and prices in order",
          "when": {
            "command": "PublishOrder",
            "payload": {
              "orderId": "3c9d8e72-5f4a-4b6c-9d0e-1f2a3b4c5d6e"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 200,
              "schemaName": "OrderPublishedResponse",
              "valueBlock": {
                "orderId": {
                  "matcher": "whenRef",
                  "path": "orderId"
                }
              }
            },
            "services": {
              "outbox": {
                "records": [
                  {
                    "type": "OrderPublished",
                    "schemaName": "OrderPublishedEvent",
                    "valueBlock": {
                      "orderId": {
                        "matcher": "whenRef",
                        "path": "orderId"
                      }
                    }
                  },
                  {
                    "type": "OrderPriced",
                    "schemaName": "OrderPricedEvent",
                    "valueBlock": {
                      "orderId": {
                        "matcher": "whenRef",
                        "path": "orderId"
                      },
                      "total": {
                        "matcher": "any",
                        "ofType": "number"
                      }
                    }
                  }
                ]
              },
              "eventBroker": {
                "records": [
                  {
                    "type": "OrderPublished",
                    "schemaName": "OrderPublishedEvent"
                  },
                  {
                    "type": "OrderPriced",
                    "schemaName": "OrderPricedEvent"
                  }
                ]
              }
            }
          }
        },
        {
          "name": "outbox order relaxed when explicitly unordered",
          "when": {
            "command": "PublishOrder",
            "payload": {
              "orderId": "3c9d8e72-5f4a-4b6c-9d0e-1f2a3b4c5d6e"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 200,
              "schemaName": "OrderPublishedResponse"
            },
            "services": {
              "outbox": {
                "ordering": "unordered",
                "records": [
                  {
                    "type": "OrderPriced",
                    "schemaName": "OrderPricedEvent"
                  },
                  {
                    "type": "OrderPublished",
                    "schemaName": "OrderPublishedEvent"
                  }
                ]
              },
              "eventBroker": {
                "ordering": "ordered",
                "records": [
                  {
                    "type": "OrderPublished",
                    "schemaName": "OrderPublishedEvent"
                  },
                  {
                    "type": "OrderPriced",
                    "schemaName": "OrderPricedEvent"
                  }
                ]
              }
            }
          }
        },
        {
          "name": "payment provider outage",
          "given": {
            "context": [
              "The payment provider is unreachable."
            ]
          },
          "when": {
            "command": "PublishOrder",
            "payload": {
              "orderId": "3c9d8e72-5f4a-4b6c-9d0e-1f2a3b4c5d6e"
            }
          },
          "prediction": {
            "type": "error",
            "errorCode": "PROVIDER_UNAVAILABLE",
            "response": {
              "status": 503,
              "schemaName": "RFC7807",
              "valueBlock": {
                "status": {
                  "matcher": "literal",
                  "value": 503
                }
              }
            },
            "services": {
              "outbox": {
                "records": []
              },
              "eventBroker": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/emit-test-file/emit-test-file.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-FEAT-001",
        "name": "Emit test file from topology",
        "context": "Toolchain",
        "aggregate": "Emitter",
        "type": "infrastructure",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "packages/feat-emit-ts/src/emit.ts"
        },
        {
          "kind": "touches",
          "glob": "packages/feat-emit-ts/**"
        },
        {
          "kind": "import",
          "symbol": "TestTopology",
          "path": "@mmmnt/feat-types"
        },
        {
          "kind": "custom",
          "text": "The emitter is a pure function of (topology, resolvedSchemas, emitterVersion)."
        },
        {
          "kind": "custom",
          "text": "Output must satisfy the deterministic header contract (ADR-0006): no timestamps."
        }
      ],
      "enforce": [
        {
          "kind": "constraint",
          "text": "render one describe block per test case in topology order"
        },
        {
          "kind": "constraint",
          "text": "inline resolved schemas as constants"
        },
        {
          "kind": "constraint",
          "text": "generated imports reference @mmmnt/feat-runtime only"
        },
        {
          "kind": "constraint",
          "text": "identical inputs must produce byte-identical output"
        },
        {
          "kind": "rejects",
          "rejectionId": "UNRESOLVED_SCHEMA",
          "text": "the topology references a schema absent from the resolved set"
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "EmitInput"
        },
        {
          "kind": "response",
          "schemaName": "EmitResult"
        },
        {
          "kind": "record",
          "schemaName": "EmittedFile"
        },
        {
          "kind": "error",
          "schemaName": "EmitError"
        }
      ],
      "scenarios": [
        {
          "name": "emits a complete test file",
          "when": {
            "command": "Emit",
            "payload": {
              "specId": "SPEC-USR-001",
              "outputPath": "create-user.test.ts"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": "OK",
              "schemaName": "EmitResult",
              "valueBlock": {
                "path": {
                  "matcher": "literal",
                  "value": "create-user.test.ts"
                },
                "bytesWritten": {
                  "matcher": "any",
                  "ofType": "number"
                }
              }
            },
            "services": {
              "filesystem": {
                "records": [
                  {
                    "type": "FILE_WRITTEN",
                    "schemaName": "EmittedFile",
                    "valueBlock": {
                      "path": {
                        "matcher": "whenRef",
                        "path": "outputPath"
                      },
                      "header": {
                        "matcher": "nested",
                        "fields": {
                          "specId": {
                            "matcher": "whenRef",
                            "path": "specId"
                          },
                          "inputsHash": {
                            "matcher": "regex",
                            "pattern": "^sha256:[0-9a-f]{64}$"
                          }
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "name": "rejects topology referencing an unresolved schema",
          "when": {
            "command": "Emit",
            "payload": {
              "specId": "SPEC-BAD-999",
              "outputPath": "bad.test.ts"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "UNRESOLVED_SCHEMA",
            "response": {
              "status": "ERR",
              "schemaName": "EmitError",
              "valueBlock": {
                "code": {
                  "matcher": "literal",
                  "value": "UNRESOLVED_SCHEMA"
                }
              }
            },
            "services": {
              "filesystem": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/flow-view/flow-view.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-AUT-003",
        "name": "Flow read model projection",
        "context": "Automation",
        "aggregate": "Flow",
        "type": "projection",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "projections/flow-view/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "projections/flow-view/**"
        },
        {
          "kind": "import",
          "symbol": "FlowViewRepository",
          "path": "core/read/flow-view-repository"
        }
      ],
      "enforce": [
        {
          "kind": "constraint",
          "text": "on FlowCreated upsert the FlowView read model keyed by flowId"
        },
        {
          "kind": "constraint",
          "text": "projection is idempotent: replaying the same event produces the same state"
        },
        {
          "kind": "constraint",
          "text": "never emit events; a projection only writes its own read model"
        }
      ],
      "contract": [
        {
          "kind": "event",
          "schemaName": "FlowCreatedEvent"
        },
        {
          "kind": "record",
          "schemaName": "FlowViewSchema"
        }
      ],
      "scenarios": [
        {
          "name": "projects a created flow into the read model",
          "delivers": [
            {
              "event": "FlowCreated",
              "payload": {
                "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b",
                "name": "Welcome",
                "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60",
                "createdAt": "2026-07-01T09:00:00Z"
              },
              "service": "eventStore"
            }
          ],
          "prediction": {
            "type": "success",
            "services": {
              "projectionStore": {
                "records": [
                  {
                    "type": "UPSERT",
                    "schemaName": "FlowViewSchema",
                    "valueBlock": {
                      "flowId": {
                        "matcher": "deliverRef",
                        "path": "flowId"
                      },
                      "name": {
                        "matcher": "deliverRef",
                        "path": "name"
                      }
                    }
                  }
                ],
                "contains": [
                  {
                    "type": "FlowView",
                    "schemaName": "FlowViewSchema",
                    "valueBlock": {
                      "flowId": {
                        "matcher": "deliverRef",
                        "path": "flowId"
                      },
                      "name": {
                        "matcher": "deliverRef",
                        "path": "name"
                      },
                      "tenantId": {
                        "matcher": "deliverRef",
                        "path": "tenantId"
                      }
                    }
                  }
                ]
              },
              "eventStore": {
                "records": []
              }
            }
          }
        },
        {
          "name": "projected state matches the golden fixture",
          "delivers": [
            {
              "event": "FlowCreated",
              "payload": {
                "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b",
                "name": "Welcome",
                "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60",
                "createdAt": "2026-07-01T09:00:00Z"
              },
              "service": "eventStore"
            }
          ],
          "prediction": {
            "type": "success",
            "services": {
              "projectionStore": {
                "records": [
                  {
                    "type": "UPSERT",
                    "schemaName": "FlowViewSchema"
                  }
                ],
                "contains": [
                  {
                    "type": "FlowView",
                    "schemaName": "FlowViewSchema",
                    "golden": "fixtures/flow-view-state.golden.json"
                  }
                ]
              },
              "eventStore": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/get-flow/get-flow.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-AUT-004",
        "name": "GetFlow query",
        "context": "Automation",
        "aggregate": "Flow",
        "type": "query",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "features/get-flow/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "features/get-flow/**"
        },
        {
          "kind": "import",
          "symbol": "FlowViewRepository",
          "path": "core/read/flow-view-repository"
        }
      ],
      "enforce": [
        {
          "kind": "constraint",
          "text": "read the FlowView by flowId from the projection store"
        },
        {
          "kind": "constraint",
          "text": "never mutate state; a query is a pure read"
        },
        {
          "kind": "rejects",
          "rejectionId": "NOT_FOUND",
          "text": "no flow view exists for the requested id"
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "GetFlowInput"
        },
        {
          "kind": "response",
          "schemaName": "FlowViewResponse"
        },
        {
          "kind": "record",
          "schemaName": "FlowViewSchema"
        },
        {
          "kind": "error",
          "schemaName": "RFC7807",
          "from": "contracts/adrs/error-format"
        }
      ],
      "scenarios": [
        {
          "name": "returns the flow view",
          "given": {
            "seeds": [
              {
                "service": "projectionStore",
                "records": [
                  {
                    "type": "FlowView",
                    "schemaName": "FlowViewSchema",
                    "values": {
                      "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b",
                      "name": "Welcome",
                      "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60"
                    }
                  }
                ]
              }
            ]
          },
          "when": {
            "command": "GetFlow",
            "payload": {
              "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 200,
              "schemaName": "FlowViewResponse",
              "valueBlock": {
                "flowId": {
                  "matcher": "whenRef",
                  "path": "flowId"
                },
                "name": {
                  "matcher": "literal",
                  "value": "Welcome"
                }
              }
            }
          }
        },
        {
          "name": "returns the flow view (golden)",
          "given": {
            "seeds": [
              {
                "service": "projectionStore",
                "records": [
                  {
                    "type": "FlowView",
                    "schemaName": "FlowViewSchema",
                    "values": {
                      "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b",
                      "name": "Welcome",
                      "tenantId": "7f0e8a52-4b1c-4d2e-9f3a-1b2c3d4e5f60"
                    }
                  }
                ]
              }
            ]
          },
          "when": {
            "command": "GetFlow",
            "payload": {
              "flowId": "5e2a7c90-1b3d-4e5f-8a6b-9c0d1e2f3a4b"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 200,
              "schemaName": "FlowViewResponse",
              "golden": "fixtures/flow-view-response.golden.json"
            }
          }
        },
        {
          "name": "unknown flow",
          "when": {
            "command": "GetFlow",
            "payload": {
              "flowId": "00000000-0000-4000-8000-000000000000"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "NOT_FOUND",
            "response": {
              "status": 404,
              "schemaName": "RFC7807",
              "valueBlock": {
                "status": {
                  "matcher": "literal",
                  "value": 404
                }
              }
            }
          }
        }
      ]
    },
    "../../corpus/suspend-user/suspend-user.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-USR-002",
        "name": "SuspendUser",
        "context": "Users",
        "aggregate": "User",
        "type": "command",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "handlers/suspend-user.ts"
        },
        {
          "kind": "touches",
          "glob": "handlers/**"
        },
        {
          "kind": "needs",
          "specId": "SPEC-USR-001"
        }
      ],
      "enforce": [
        {
          "kind": "constraint",
          "text": "only admins may suspend users"
        },
        {
          "kind": "rejects",
          "rejectionId": "UNAUTHORIZED",
          "text": "the caller is not an admin"
        },
        {
          "kind": "rejects",
          "rejectionId": "UNKNOWN_USER",
          "text": "no user exists with the given email"
        },
        {
          "kind": "constraint",
          "text": "record the suspension time from the injected clock"
        }
      ],
      "contract": [
        {
          "kind": "input",
          "schemaName": "SuspendUserInput"
        },
        {
          "kind": "response",
          "schemaName": "SuspendResult"
        },
        {
          "kind": "record",
          "schemaName": "UserRow"
        },
        {
          "kind": "error",
          "schemaName": "ErrorResponse"
        }
      ],
      "scenarios": [
        {
          "name": "admin suspends a user",
          "given": {
            "clock": "2026-07-16T00:00:00Z",
            "executes": [
              {
                "command": "CreateUser",
                "payload": {
                  "email": "alice@example.com",
                  "name": "Alice"
                }
              }
            ]
          },
          "when": {
            "command": "SuspendUser",
            "actor": "admin",
            "payload": {
              "email": "alice@example.com"
            }
          },
          "prediction": {
            "type": "success",
            "response": {
              "status": 200,
              "schemaName": "SuspendResult",
              "valueBlock": {
                "status": {
                  "matcher": "literal",
                  "value": "suspended"
                }
              }
            },
            "services": {
              "database": {
                "records": [
                  {
                    "type": "UPDATE",
                    "schemaName": "UserRow",
                    "valueBlock": {
                      "email": {
                        "matcher": "whenRef",
                        "path": "email"
                      },
                      "status": {
                        "matcher": "literal",
                        "value": "suspended"
                      },
                      "suspendedAt": {
                        "matcher": "literal",
                        "value": "2026-07-16T00:00:00Z"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "name": "anonymous caller is rejected",
          "when": {
            "command": "SuspendUser",
            "actor": "anonymous",
            "payload": {
              "email": "alice@example.com"
            }
          },
          "prediction": {
            "type": "rejection",
            "rejectionId": "UNAUTHORIZED",
            "response": {
              "status": 401,
              "schemaName": "ErrorResponse",
              "valueBlock": {
                "code": {
                  "matcher": "literal",
                  "value": "UNAUTHORIZED"
                }
              }
            },
            "services": {
              "database": {
                "records": []
              }
            }
          }
        },
        {
          "name": "unknown users are rejected regardless of email shape",
          "when": {
            "command": "SuspendUser",
            "actor": "admin",
            "payload": {
              "email": {
                "$placeholder": "email"
              }
            }
          },
          "examples": [
            {
              "email": "missing@example.com",
              "code": "UNKNOWN_USER",
              "msg": "missing"
            },
            {
              "email": "also.missing@example.com",
              "code": "UNKNOWN_USER",
              "msg": "missing"
            }
          ],
          "prediction": {
            "type": "rejection",
            "rejectionId": "<code>",
            "response": {
              "status": 404,
              "schemaName": "ErrorResponse",
              "valueBlock": {
                "code": {
                  "matcher": "placeholder",
                  "name": "code"
                },
                "message": {
                  "matcher": "regex",
                  "pattern": {
                    "$placeholder": "msg"
                  }
                }
              }
            },
            "services": {
              "database": {
                "records": []
              }
            }
          }
        }
      ]
    },
    "../../corpus/ship-order/ship-order.ir.json": {
      "featVersion": "1.0",
      "identity": {
        "id": "SPEC-ORD-002",
        "name": "ShipOrder Saga",
        "context": "Fulfillment",
        "aggregate": "Order",
        "type": "saga",
        "status": "agreed"
      },
      "construct": [
        {
          "kind": "handler",
          "path": "sagas/ship-order/handler.ts"
        },
        {
          "kind": "touches",
          "glob": "sagas/ship-order/**"
        },
        {
          "kind": "import",
          "symbol": "OrderSaga",
          "path": "core/domain/order-saga"
        }
      ],
      "enforce": [
        {
          "kind": "constraint",
          "text": "when OrderPublished and then OrderPriced have both arrived, request shipment"
        },
        {
          "kind": "constraint",
          "text": "the shipment request carries the order id from the first event and the total from the second"
        },
        {
          "kind": "constraint",
          "text": "never request shipment before both events have arrived"
        }
      ],
      "contract": [
        {
          "kind": "event",
          "schemaName": "OrderPublishedEvent"
        },
        {
          "kind": "event",
          "schemaName": "OrderPricedEvent"
        },
        {
          "kind": "record",
          "schemaName": "ShipmentRequestedEvent"
        }
      ],
      "scenarios": [
        {
          "name": "requests shipment after the full sequence",
          "delivers": [
            {
              "event": "OrderPublished",
              "payload": {
                "orderId": "3c9d8e72-5f4a-4b6c-9d0e-1f2a3b4c5d6e",
                "publishedAt": "2026-07-01T10:00:00Z"
              },
              "service": "eventBroker"
            },
            {
              "event": "OrderPriced",
              "payload": {
                "orderId": "3c9d8e72-5f4a-4b6c-9d0e-1f2a3b4c5d6e",
                "total": 129.5
              },
              "service": "eventBroker"
            }
          ],
          "prediction": {
            "type": "success",
            "services": {
              "outbox": {
                "records": [
                  {
                    "type": "ShipmentRequested",
                    "schemaName": "ShipmentRequestedEvent",
                    "valueBlock": {
                      "orderId": {
                        "matcher": "deliverRef",
                        "path": "orderId",
                        "index": 0
                      },
                      "total": {
                        "matcher": "deliverRef",
                        "path": "total",
                        "index": 1
                      }
                    }
                  }
                ]
              },
              "eventBroker": {
                "records": []
              }
            }
          }
        }
      ]
    }
  }
};

const CASES: HarnessCase[] = [
  {
    "anchor": "SPEC-CORE-001 › \"parses the founding exemplar (create-flow)\"",
    "name": "parses the founding exemplar (create-flow)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/create-flow/create-flow.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/create-flow/create-flow.feat",
        "config": "corpus/create-flow/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the CRUD exemplar (create-user)\"",
    "name": "parses the CRUD exemplar (create-user)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/create-user/create-user.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/create-user/create-user.feat",
        "config": "corpus/create-user/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the seeds exemplar (tenant-at-limit)\"",
    "name": "parses the seeds exemplar (tenant-at-limit)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/tenant-at-limit/tenant-at-limit.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/tenant-at-limit/tenant-at-limit.feat",
        "config": "corpus/tenant-at-limit/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the ordering exemplar (publish-order)\"",
    "name": "parses the ordering exemplar (publish-order)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/publish-order/publish-order.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/publish-order/publish-order.feat",
        "config": "corpus/publish-order/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the compiler-shaped exemplar (emit-test-file)\"",
    "name": "parses the compiler-shaped exemplar (emit-test-file)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/emit-test-file/emit-test-file.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/emit-test-file/emit-test-file.feat",
        "config": "corpus/emit-test-file/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the projection exemplar (flow-view)\"",
    "name": "parses the projection exemplar (flow-view)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/flow-view/flow-view.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/flow-view/flow-view.feat",
        "config": "corpus/flow-view/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the query exemplar (get-flow)\"",
    "name": "parses the query exemplar (get-flow)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/get-flow/get-flow.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/get-flow/get-flow.feat",
        "config": "corpus/get-flow/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the expressiveness exemplar (suspend-user)\"",
    "name": "parses the expressiveness exemplar (suspend-user)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/suspend-user/suspend-user.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/suspend-user/suspend-user.feat",
        "config": "corpus/suspend-user/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"parses the saga exemplar (ship-order)\"",
    "name": "parses the saga exemplar (ship-order)",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "BuiltSpec",
        "golden": "../../corpus/ship-order/ship-order.ir.json"
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "corpus/ship-order/ship-order.feat",
        "config": "corpus/ship-order/feat.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[1]",
    "name": "rejects invalid specs with the precise code › row[1]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "MISSING_PRAGMA",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "MISSING_PRAGMA"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/missing-pragma.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[2]",
    "name": "rejects invalid specs with the precise code › row[2]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "UNSUPPORTED_VERSION",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "UNSUPPORTED_VERSION"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/unsupported-version.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[3]",
    "name": "rejects invalid specs with the precise code › row[3]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "MALFORMED_SYNTAX",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "MALFORMED_SYNTAX"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/malformed-syntax.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[4]",
    "name": "rejects invalid specs with the precise code › row[4]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "UNKNOWN_SERVICE_KEY",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "UNKNOWN_SERVICE_KEY"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/unknown-service.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[5]",
    "name": "rejects invalid specs with the precise code › row[5]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "UNKNOWN_COMMAND",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "UNKNOWN_COMMAND"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/unknown-command.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[6]",
    "name": "rejects invalid specs with the precise code › row[6]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "UNDECLARED_SCHEMA",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "UNDECLARED_SCHEMA"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/undeclared-schema.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[7]",
    "name": "rejects invalid specs with the precise code › row[7]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "UNKNOWN_ACTOR",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "UNKNOWN_ACTOR"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/unknown-actor.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[8]",
    "name": "rejects invalid specs with the precise code › row[8]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "DUPLICATE_SCENARIO_NAME",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "DUPLICATE_SCENARIO_NAME"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/duplicate-scenario.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[9]",
    "name": "rejects invalid specs with the precise code › row[9]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "TRIGGER_MISMATCH",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "TRIGGER_MISMATCH"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/trigger-mismatch.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[10]",
    "name": "rejects invalid specs with the precise code › row[10]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "QUERY_SIDE_EFFECT",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "QUERY_SIDE_EFFECT"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/query-side-effect.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[11]",
    "name": "rejects invalid specs with the precise code › row[11]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "INCOMPLETE_PREDICTION",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "INCOMPLETE_PREDICTION"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/incomplete-prediction.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-CORE-001 › \"rejects invalid specs with the precise code\" › row[12]",
    "name": "rejects invalid specs with the precise code › row[12]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "MISSING_MINIMUM",
      "response": {
        "status": "ERR",
        "schemaName": "ParseError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "MISSING_MINIMUM"
          }
        }
      }
    },
    "when": {
      "command": "Parse",
      "payload": {
        "spec": "packages/feat-core/fixtures/bad/missing-minimum.feat",
        "config": "packages/feat-core/fixtures/parse.config.json"
      }
    }
  }
];

describe("SPEC-CORE-001: Parse a .feat file to BuiltSpec IR", () => {
  let h: Harness;
  beforeAll(async () => {
    h = await createHarness({ configPath: CONFIG_PATH });
  });
  afterAll(async () => {
    await h.teardown();
  });
  for (const c of CASES) {
    it(c.name, async () => {
      await h.runCase(c, INLINE);
    });
  }
});
