// AUTO-GENERATED by feat emit — do not edit manually
// Source: packages/feat-runtime/load-config.feat (SPEC-RT-001)
// Language: feat 1.0 · Emitter: @mmmnt/feat-emit-ts@0.1.0
// Inputs-hash: sha256:70bf1f94bb998d743941d8e86aed64b18b286890bf4d36e58524a9b15bce3b94

import { describe, it, beforeAll, afterAll } from "vitest";
import { createHarness, type Harness, type HarnessCase, type InlineData } from "@mmmnt/feat-runtime";

const INLINE: InlineData = {
  "schemas": {
    "LoadConfigInput": {
      "type": "object",
      "required": [
        "path"
      ],
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "FeatConfigResult": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "$id": "https://feat.dev/schemas/feat.config.json",
      "title": "FeatConfig",
      "description": "feat.config.json — service, adapter, and pipeline configuration. Loaded once per run (INV-8); validated by @mmmnt/feat-runtime loadConfig (ADR-0001).",
      "type": "object",
      "required": [
        "schemas",
        "services",
        "specs"
      ],
      "additionalProperties": false,
      "properties": {
        "featVersion": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+$",
          "description": "Language version this project targets (ADR-0005)."
        },
        "schemas": {
          "type": "object",
          "required": [
            "adapter"
          ],
          "additionalProperties": false,
          "properties": {
            "adapter": {
              "$ref": "#/definitions/moduleSpecifier"
            }
          }
        },
        "response": {
          "type": "object",
          "description": "Required only when specs use when:/execute (deliver-only projects omit it); enforced cross-file at parse time (ADR-0009/0011).",
          "required": [
            "adapter",
            "commands"
          ],
          "additionalProperties": false,
          "properties": {
            "adapter": {
              "$ref": "#/definitions/moduleSpecifier"
            },
            "invoke": {
              "type": "object",
              "description": "Adapter-wide invocation config (baseUrl/headers, host/protoPath).",
              "additionalProperties": true
            },
            "commands": {
              "type": "object",
              "description": "Command routing (ADR-0009): CommandName -> adapter-specific invocation shape (HTTP: {method, path}; handler: {module, export}). Closed command space: every command used in when:/execute must exist here — validated at parse time.",
              "minProperties": 1,
              "additionalProperties": {
                "type": "object",
                "additionalProperties": true
              }
            },
            "actors": {
              "type": "object",
              "description": "Actor registry (ADR-0012): named actors with adapter-specific auth material (HTTP: headers/token; handler: context object). 'default' names the actor used when a trigger has no as-clause; 'anonymous' is reserved (unauthenticated) and never declared. Closed actor space — validated at parse time.",
              "properties": {
                "default": {
                  "type": "string"
                }
              },
              "additionalProperties": {
                "type": "object",
                "additionalProperties": true
              }
            }
          }
        },
        "services": {
          "type": "object",
          "description": "User-defined service keys — the only valid prediction targets (INV-7).",
          "minProperties": 1,
          "additionalProperties": {
            "type": "object",
            "required": [
              "adapter",
              "consistency"
            ],
            "additionalProperties": false,
            "properties": {
              "adapter": {
                "$ref": "#/definitions/moduleSpecifier"
              },
              "consistency": {
                "enum": [
                  "acid",
                  "strong",
                  "eventual"
                ]
              },
              "convergenceTimeout": {
                "type": "integer",
                "minimum": 0,
                "description": "Milliseconds to wait before capturing eventual services. Required when consistency is 'eventual'."
              },
              "absenceTimeout": {
                "type": "integer",
                "minimum": 0,
                "description": "Optional shorter wait for absence proofs on eventual services (ADR-0014 tuning knob)."
              },
              "options": {
                "type": "object",
                "description": "Adapter-specific options (e.g. fs adapter scope).",
                "additionalProperties": true
              }
            }
          }
        },
        "specs": {
          "type": "object",
          "required": [
            "dir",
            "pattern",
            "contractPattern",
            "outputPattern"
          ],
          "additionalProperties": false,
          "properties": {
            "dir": {
              "type": "string"
            },
            "pattern": {
              "type": "string"
            },
            "contractPattern": {
              "type": "string"
            },
            "outputPattern": {
              "type": "string"
            }
          }
        },
        "report": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "format": {
              "type": "array",
              "items": {
                "enum": [
                  "console",
                  "junit"
                ]
              },
              "minItems": 1
            },
            "junitOutput": {
              "type": "string"
            }
          }
        }
      },
      "definitions": {
        "moduleSpecifier": {
          "type": "string",
          "minLength": 1,
          "description": "npm package name or local path; the module must export createAdapter(config) (INV-10, ADR-0001)."
        }
      }
    },
    "ConfigError": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "enum": [
            "CONFIG_NOT_FOUND",
            "INVALID_CONFIG",
            "MISSING_CONVERGENCE_TIMEOUT"
          ]
        },
        "message": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "detail": {
          "type": "string"
        }
      }
    }
  },
  "goldens": {}
};

const CASES: HarnessCase[] = [
  {
    "anchor": "SPEC-RT-001 › \"loads a valid config\"",
    "name": "loads a valid config",
    "prediction": {
      "type": "success",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "response": {
        "status": "OK",
        "schemaName": "FeatConfigResult",
        "valueBlock": {
          "featVersion": {
            "matcher": "literal",
            "value": "1.0"
          },
          "services": {
            "matcher": "nested",
            "fields": {
              "filesystem": {
                "matcher": "nested",
                "fields": {
                  "consistency": {
                    "matcher": "literal",
                    "value": "acid"
                  }
                }
              }
            }
          }
        }
      }
    },
    "given": {
      "context": [
        "A well-formed config exists at the fixture path."
      ]
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/valid.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"missing file\"",
    "name": "missing file",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "CONFIG_NOT_FOUND",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "CONFIG_NOT_FOUND"
          },
          "path": {
            "matcher": "whenRef",
            "path": "path"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/does-not-exist.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"eventual service without convergence timeout\"",
    "name": "eventual service without convergence timeout",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "MISSING_CONVERGENCE_TIMEOUT",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "MISSING_CONVERGENCE_TIMEOUT"
          },
          "detail": {
            "matcher": "regex",
            "pattern": "eventStore"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/missing-timeout.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"schema-invalid configs are rejected\" › row[1]",
    "name": "schema-invalid configs are rejected › row[1]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "INVALID_CONFIG",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "INVALID_CONFIG"
          },
          "detail": {
            "matcher": "regex",
            "pattern": "services"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/no-services.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"schema-invalid configs are rejected\" › row[2]",
    "name": "schema-invalid configs are rejected › row[2]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "INVALID_CONFIG",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "INVALID_CONFIG"
          },
          "detail": {
            "matcher": "regex",
            "pattern": "consistency"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/bad-consistency.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"schema-invalid configs are rejected\" › row[3]",
    "name": "schema-invalid configs are rejected › row[3]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "INVALID_CONFIG",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "INVALID_CONFIG"
          },
          "detail": {
            "matcher": "regex",
            "pattern": "commands"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/empty-commands.config.json"
      }
    }
  },
  {
    "anchor": "SPEC-RT-001 › \"schema-invalid configs are rejected\" › row[4]",
    "name": "schema-invalid configs are rejected › row[4]",
    "prediction": {
      "type": "rejection",
      "services": {
        "filesystem": {
          "ordering": "ordered",
          "records": []
        }
      },
      "rejectionId": "INVALID_CONFIG",
      "response": {
        "status": "ERR",
        "schemaName": "ConfigError",
        "valueBlock": {
          "code": {
            "matcher": "literal",
            "value": "INVALID_CONFIG"
          },
          "detail": {
            "matcher": "regex",
            "pattern": "JSON"
          }
        }
      }
    },
    "when": {
      "command": "LoadConfig",
      "payload": {
        "path": "fixtures/not-json.config.json"
      }
    }
  }
];

describe("SPEC-RT-001: Load and validate feat.config.json", () => {
  let h: Harness;
  beforeAll(async () => {
    h = await createHarness({ configPath: "../../feat.config.json" });
  });
  afterAll(async () => {
    await h.teardown();
  });
  for (const c of CASES) {
    it(c.name, async () => {
      await h.runCase(c, INLINE);
    });
  }
});
